Resources:
  EC2:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - Ref: EC2SecurityGroup
      ImageId: ami-09d4a659cdd8677be
      KeyName: ${self:provider.ssh_key}
      Tags:
        - Key: Name
          Value:  Open Telemetry Collector

  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
        GroupDescription: ALL TCP
        SecurityGroupIngress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  # ${self:privateEnvironment.SNS.OPEN_TELEMETRY_TOPIC_NAME}
